name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Remove old lockfile
        run: rm -f package-lock.json

            - name: Install dependencies with legacy-peer-deps
        run: npm install --legacy-peer-deps


      - name: Build project
        run: npm run build
